"""first-migration

Revision ID: ae8e7a75c865
Revises: 
Create Date: 2022-11-11 10:50:57.304237

"""

import os
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae8e7a75c865'
down_revision = None
branch_labels = None
depends_on = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_completed_content_blocks_id', table_name='completed_content_blocks')
    op.drop_table('completed_content_blocks')
    op.drop_index('ix_content_blocks_id', table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index('ix_sections_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_student_courses_id', table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_profiles_id', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
                            sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                            sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                            sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"),
                                      autoincrement=True, nullable=False),
                            sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                            sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                            sa.PrimaryKeyConstraint('id', name='users_pkey'),
                            postgresql_ignore_search_path=False
                            )
    op.add_column('users',
                  sa.Column('role', sa.Enum('teacher', 'student', name='role'), autoincrement=False, nullable=False)),
    # Python code to open and read file and then dumping (inserting) into users table
    with open(os.path.join(os.path.dirname(__file__), "../data/students.json")) as f:
        student_data = f.read()

    op.bulk_insert(users, json.loads(student_data))

    op.create_table('courses',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='courses_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='courses_pkey')
                    )
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('sections',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sections_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='sections_course_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='sections_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index('ix_sections_id', 'sections', ['id'], unique=False)
    op.create_table('profiles',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profiles_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
                    )
    op.create_index('ix_profiles_id', 'profiles', ['id'], unique=False)
    op.create_table('content_blocks',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('content_blocks_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='content_blocks_section_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='content_blocks_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.add_column("content_blocks", sa.Column('type', sa.Enum(
        'lesson', 'quiz', 'assignment', name='contenttype'), autoincrement=False, nullable=True))
    op.create_index('ix_content_blocks_id', 'content_blocks', ['id'], unique=False)

    op.create_table('student_courses',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_courses_course_id_fkey'),
                    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='student_courses_student_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='student_courses_pkey')
                    )
    op.create_index('ix_student_courses_id', 'student_courses', ['id'], unique=False)
    op.create_table('completed_content_blocks',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('content_block_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['content_block_id'], ['content_blocks.id'],
                                            name='completed_content_blocks_content_block_id_fkey'),
                    sa.ForeignKeyConstraint(['student_id'], ['users.id'],
                                            name='completed_content_blocks_student_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='completed_content_blocks_pkey')
                    )
    op.create_index('ix_completed_content_blocks_id', 'completed_content_blocks', ['id'], unique=False)
    # ### end Alembic commands ###
